# Generated by Django 2.1.2 on 2018-10-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='last_name',
            new_name='quantity',
        ),
    ]
